### ISSUE TITLE
Road Map for this learning project.

### ISSUE THREAD

**Issue by nihanmubashshir** [nihanmubashshir/lp-ecom#1]
- [ ] Products CRUD.
- [ ] Build a simple Admin panel to streamline the adding products and upgrading them.
- [ ] Order.
- [ ] Customer.
- [ ] Store front API.
- [ ] Build a simple storefront.
- [ ] Refactor and revise.
- [ ] Build a Testing System.
- [ ] Authentication System
